# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
default_language_version:
  node: system
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: trailing-whitespace
        exclude: ^API.md||.github/$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.21.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        exclude: |
          (?x)(
              ^.github/|
              ^.projen/|
              ^.mergify.yml|
              ^.*.json |
              ^API.md |
              ^README.md
          )
  - repo: https://github.com/dontirun/text-prepender
    rev: v0.1.0
    hooks:
      - id: text-prepender
        exclude: |
          (?x)(
              ^.github/|
              ^.projen/|
              ^.mergify.yml|
              ^.*.json |
              ^API.md 
          )
  - repo: local
    hooks:
      - id: append-api-to-readme
        name: append-api-to-readme
        entry: scripts/append-api-docs-to-readme.sh
        language: script
        pass_filenames: false
        files: API.md
