################
# Install 
################
- name: Install Squid
  yum:
    name: squid
    state: present

- name: Create {{ squid.squid_resources_path }} if it does not exist
  ansible.builtin.file:
    path: "{{ squid.squid_resources_path }}"
    state: directory
    mode: '0755'

- name: Copy squid.conf
  ansible.builtin.template:
    src: "{{ squid.squid_config_files_path }}/squid.conf"
    dest: "{{ squid.squid_resources_path }}/squid.conf"
    mode: 640
  notify:
  - Restart squid

- name: Copy approved-domains.txt
  ansible.builtin.template:
    src: "{{ squid.squid_config_files_path }}/approved-domains.conf"
    dest: "{{ squid.squid_resources_path }}/squid.allowed.sites.txt"
    mode: 640
  notify:
  - Restart squid

- name: Generate dummy certificate
  ansible.builtin.shell: |
    openssl req -x509 -newkey rsa:4096 \
    -keyout {{ squid.squid_resources_path }}/cert.pem \
    -out {{ squid.squid_resources_path }}/cert.pem \
    -days 3650 \
    -subj "/C=XX/ST=XX/L=squid/O=squid/CN=squid" \
    -nodes

- name: Start and enable Squid
  ansible.builtin.service:
    name: squid
    state: started
    enabled: yes

- name: Squid log rotation cron
  ansible.builtin.cron:
    name: "rotate squid logs"
    special_time: daily
    job: "squid -k rotate"
